### PR TITLE
AboutUs.adoc: Add for Wei Jie

### LINKED ISSUE #56: Update About Me Page
Add the following:
1. Photo
2. Role and Responsibilities

### PR DESCRIPTION
**Pull request by Cherweijie**
Added image and updated portfolio link to github

### CODE REVIEW

**Review by khsc96 — CHANGES_REQUESTED** [review]
Portfolio not set-up properly

**Review by JeremyLoh — CHANGES_REQUESTED** [review]
The image should be named via the following format: [githbub_username_in_lower_case].png
It is currently 2103dp.jpg
It should be cherweijie.png
Remember to change your display picture link in AboutUs.adoc to png format as well!

**Review by JeremyLoh — APPROVED** [review]
Looks good to merge.

**Review by khsc96 — APPROVED** [review]
LGTM. Good job

**Pull request merged**
