### PR TITLE
Implement Done Command

### LINKED ISSUE #149: Add Done to UML diagram, Java class and test file

### PR DESCRIPTION
**Pull request by Cherweijie**
#149

### CODE REVIEW

**Review by Amoscheong97 — APPROVED** [review]
Looks ok to me. Just make sure the PR pass all checks

**Review by Amoscheong97 — CHANGES_REQUESTED** [review]
Ensure that you pass Travis and Appveyor for this PR

**Review by JeremyLoh — COMMENTED** [review]
Why are there email fields for the code? I think it has already been removed, based on the UG? I think you can pull changes from upstream master, maybe can update the code

**Review by JeremyLoh — APPROVED** [review]
Remember to update UG and DG after we have merged Amos's PR for insert command #191, if you are going to add the email field. Thanks!

**Review by Amoscheong97 — APPROVED** [review]
LGTM

**Review by JeremyLoh — APPROVED** [review]
LGTM

**Review by Exeexe93 — APPROVED** [review]
LGTM

**Pull request merged**
