### PR TITLE
UserGuide.adoc: Add return feature

### LINKED ISSUE #63: Update User guide documentation for Returns feature (Week 7)
Update User guide documentation for Returns feature by Week 7

### PR DESCRIPTION
**Pull request by Cherweijie**
#63

### CODE REVIEW

**Review by Exeexe93 — CHANGES_REQUESTED** [review]
Please also add the return example into the command summary.

**Comment by Exeexe93** [comment]
Please note that the command should list in alphabetical order. So the return command should be behind list command.

**Review by Exeexe93 — APPROVED** [review]
Look good to merge.

**Review by JeremyLoh — APPROVED** [review]
LGTM

**Pull request merged**
