### PR TITLE
Update ModelClassDiagram class/interface names and related test classes

### LINKED ISSUE #138: Update ModelClassDiagram, Rename related classes/interfaces

### PR DESCRIPTION
**Pull request by JeremyLoh**
Change references from **'Address'** to **'Order'**. 

Affected classes/interfaces: 
1. AddressBook -> OrderBook
2. ReadOnlyAddressBook -> ReadOnlyOrderBook
3. UniqueAddressList -> UniqueOrderList
4. Person -> Order

The package names are still the same. Only a subset of test classes have been changed. 

The updated ModelClassDiagram is shown below.
image

### CODE REVIEW

**Review by Exeexe93 — APPROVED** [review]
Thanks for the effort refactoring by renaming all persons or addressbook to orders and orderbook respectively. LGTM.

**Review by Amoscheong97 — APPROVED** [review]
Good to merge. Thank you for the effort of renaming all the Person to Order for so many files.

**Review by khsc96 — APPROVED** [review]
LGTM

**Review by Cherweijie — APPROVED** [review]
Good job, Jeremy! Thanks for taking the initiative to kickstart the refactoring process.

**Pull request merged**
